name: CI - Pytest with DVC + CML

on:
  push:
    branches:
      - dev       # run on any commit to dev
  pull_request:
    branches:
      - main      # run on PR to main from dev

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install dvc[gcs] pytest dvc-gs

      # 4️⃣ Configure DVC remote
      - name: Configure DVC remote
        run: |
          if ! dvc remote list | grep -q gcsremote; then
            dvc remote add -d gcsremote gs://mlops_b
          fi
          dvc remote list


      # 5️⃣ Pull DVC artifacts
      - name: Pull data and model from DVC
        run: |
          dvc pull data/raw/iris.csv.dvc
          dvc pull tmp/model.joblib.dvc
          ls -R

      # 6️⃣ Run pytest
      - name: Run pytest and save results
        run: |
          pytest -v tests/test_evaluate.py --maxfail=1 --disable-warnings | tee result.log

      # 7️⃣ Post results to PR using CML
      - name: Post pytest results as PR comment
        uses: iterative/setup-cml@v2
        with:
          args: result.log
        env:
          CML_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
